# Generated by Django 4.1.1 on 2022-09-22 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viajeros', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Viajeros',
        ),
    ]
