# Generated by Django 4.1.1 on 2022-09-22 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viajeros', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viajeros',
            options={'verbose_name': 'viaje', 'verbose_name_plural': 'viajeros'},
        ),
    ]
