# Generated by Django 4.1.1 on 2022-09-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ref_familiares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreRef_familiares', models.CharField(help_text='Ingrese el Nombre del ref familiar', max_length=100)),
                ('apellidoRef_familiares', models.EmailField(help_text='Ingrese el apellido del ref familiar', max_length=100)),
                ('direccionRef_familiares', models.CharField(help_text='Ingrese la Direccion del ref familiar', max_length=100)),
                ('telefonoRef_familiares', models.CharField(help_text='Ingrese el Telefono del ref familiar', max_length=12)),
            ],
            options={
                'verbose_name': 'ref familiar',
                'verbose_name_plural': 'ref familiares',
            },
        ),
    ]
