# Generated by Django 4.1.1 on 2022-09-22 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ref_familiares', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ref_familiares',
        ),
    ]
