# Generated by Django 4.1.1 on 2022-09-23 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viajes', '0002_delete_viajeros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'destino',
                'verbose_name_plural': 'destinos',
            },
        ),
        migrations.CreateModel(
            name='Origen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'origen',
                'verbose_name_plural': 'origenes',
            },
        ),
        migrations.CreateModel(
            name='Viajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('stockmin', models.IntegerField(verbose_name='Stock Minimo')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('codigoviaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='viajes.origen')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': ' productos',
            },
        ),
    ]
