# Generated by Django 4.1.1 on 2022-09-23 00:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viajes',
            old_name='nombre',
            new_name='ndeplazas',
        ),
        migrations.RemoveField(
            model_name='viajes',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='viajes',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='viajes',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='viajes',
            name='stockmin',
        ),
        migrations.AddField(
            model_name='viajes',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Actual'),
        ),
    ]
